name: AI Intel Bot (Email)

on:
  schedule:
    - cron: '0 4 * * *'  # 04:00 UTC = 09:00 PKT
    - cron: '0 12 * * *' # 12:00 UTC = 17:00 PKT
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create service account key file
        shell: bash
        run: |
          echo "$GCP_SERVICE_ACCOUNT_JSON" > sa.json

      - name: Run bot
        env:
          GCP_SERVICE_ACCOUNT_JSON_FILE: ${{ github.workspace }}/sa.json
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_TAB: ${{ secrets.SHEET_TAB }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GMAIL_TO: ${{ secrets.GMAIL_TO }}
        run: |
          python src/main.py

