- name: Install deps
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

- name: Create service account key file
  run: |
    echo '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}' > sa.json

- name: Run bot
  env:
    GCP_SERVICE_ACCOUNT_JSON_FILE: ${{ github.workspace }}/sa.json
    SHEET_ID: ${{ secrets.SHEET_ID }}
    SHEET_TAB: ${{ secrets.SHEET_TAB }}
    GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    GMAIL_USER: ${{ secrets.GMAIL_USER }}
    GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
    GMAIL_TO: ${{ secrets.GMAIL_TO }}
  run: |
    python src/main.py
